dataset_name: "egd-cxr"

input_path:
  gaze_raw: /home/qtnguy50/gaze-01-baseline/datasets/gaze_data/egd_cxr/transcripts
  dicom_raw: /home/qtnguy50/gaze-01-baseline/datasets/dicom_raw
  segmentation_dir: /home/qtnguy50/gaze-01-baseline/datasets/gaze_data/egd_cxr/transcripts/audio_segmentation_transcripts
  transcripts_dir: /home/qtnguy50/gaze-01-baseline/datasets/gaze_data/egd_cxr/transcripts/audio_segmentation_transcripts

split_files:
  dir: /home/qtnguy50/gaze-01-baseline/configs/splits/fold1

train:
  classes: ["CHF", "pneumonia", "Normal"]
  batch_size: 32
  epochs: 50
  max_fixations: 30  # Match temporal and unet for consistent data loading
  num_workers: 2
  lr: 3.0e-4
  weight_decay: 1.0e-4
  label_smoothing: 0.05
  patience: 50
  use_weighted_sampler: false
  lambda_txt: 1.0
  max_txt_len: 64

model:
  d_img: 128

output_path:
  checkpoint_dir: runs/checkpoints/gazegnn
  best_ckpt_name: gazegnn_best.pt

options:
  model: gazegnn
  image_backbone: pvig_ti_224_gelu

